# Generated by Django 3.2.15 on 2024-03-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocation',
            options={'verbose_name': 'геолокация', 'verbose_name_plural': 'геолокации'},
        ),
    ]
