FROM python:3.11

WORKDIR /opt/app

COPY backend .
COPY .env .
COPY requirements.txt .

RUN pip install -r requirements.txt

RUN python manage.py collectstatic --noinput

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
